# Google Analytics
google_analytics: 
  id: G-0797LLHMZP  # 여기에 측정 ID를 입력하세요

# 사이트 설정
title: TG's Programming Blog
description: >-
  Deep dives into C++, async multi-threading, rendering, Windows development, and game programming.
baseurl: "" # 중요: 이 값이 비어있어야 합니다
url: "https://tgparkk.github.io" 

# 빌드 설정
markdown: kramdown
highlighter: rouge

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 테마 설정
sass:
  sass_dir: _sass
  style: compressed

# 기본값
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"